---

- name: "Ensure Grafana YUM Repository is present"
  yum_repository:
    name: "grafana"
    description: "Grafana Repository"
    baseurl: "{{ __grafana_yum_repository_url }}"
    gpgcheck: yes
    gpgkey: "{{ __grafana_yum_repository_gpgkey }}"

- name: "Ensure Grafana package is installed"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - grafana

- name: "Ensure the Grafana service is enabled"
  service:
    name: "{{ grafana_service_name }}"
    enabled: yes

- name: "Ensure the Grafana service is started"
  service:
    name: "{{ grafana_service_name }}"
    state: started
